 version: 1
 formatters:
   detailed:
      format: "%(asctime)s [%(levelname)s] %(funcName)s:  %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
 handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: detailed
      stream: ext://sys.stdout
 loggers:
   betl_src_poc_logger:
      level: INFO
      handlers: [console]
      propagate: no
 root:
  level: INFO
  handlers: [console]
